
<table width="100" border="0" cellspacing="0" cellpadding="0" align="left">
<tr>
<td valign="top"><img src="../img/thumb/gl_glukoza.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Glukoza</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_glukoza_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_glukoza_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br></div></td>
<td valign="top"><img src="../img/thumb/gl_fox.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Fox Nurse</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_fox_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_fox_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_fox_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_fox_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_fox_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_fox_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_fox_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_fox_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/gl_bear.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Bear</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_bear_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_bear_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_bear_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_bear_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_bear_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_bears_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
</tr>

<tr><td><img src="../img/0.gif" alt="" width="10" height="40" border="0"></td><td></td><td></td><td></td><td></td><td></td></tr>

<tr>
<td valign="top"><img src="../img/thumb/gl_paratrooper.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Paratrooper</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_paratrooper_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_paratrooper_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_paratrooper_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_paratrooper_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_paratrooper_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_paratrooper_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_paratrooper_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_paratrooper_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/gl_builder.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Builder</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_builder_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_builder_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_builder_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_builder_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_builder_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_builder_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_builder_Work')" class = submenu>Work<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_builder_Work.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_builder_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_builder_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/gl_beaver.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Beaver</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_beaver_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_beaver_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_beaver_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_beaver_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_beaver_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_beavers_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_beaver_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_beaver_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_beaver_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_beaver_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
</tr>

<tr><td><img src="../img/0.gif" alt="" width="10" height="40" border="0"></td><td></td><td></td><td></td><td></td><td></td></tr>

<tr>
<td valign="top"><img src="../img/thumb/gl_elephant1.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Elephant</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_elephant1_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_elephant1_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_elephant1_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_elephant1_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_elephant1_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_elephant1s_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_elephant1_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_elephant1_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/gl_jeep.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Jeep</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_jeep_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_jeep_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_jeep_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_jeeps_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_jeep_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_jeep_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_jeep_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_jeep_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/gl_mole.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Mole</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_mole_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_mole_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_mole_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_mole_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_mole_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_moles_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_mole_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_mole_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
</tr>

<tr><td><img src="../img/0.gif" alt="" width="10" height="40" border="0"></td><td></td><td></td><td></td><td></td><td></td></tr>

<tr>
<td valign="top"><img src="../img/thumb/gl_ostrich.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Ostrich</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_ostrich_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_ostrich_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_ostrich_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_ostrichs_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_ostrich_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_ostrich_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/gl_shorty.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Shorty</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_shorty_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_shorty_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_shorty_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_shorty_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=gl_shorty_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/gl_shorty_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/sw_boar.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Boar</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_boar_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_boar_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_boar_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_boar_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_boar_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_boars_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
</tr>

<tr><td><img src="../img/0.gif" alt="" width="10" height="40" border="0"></td><td></td><td></td><td></td><td></td><td></td></tr>

<tr>
<td valign="top"><img src="../img/thumb/sw_builder.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Builder</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_builder_Work')" class = submenu>Work<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_builder_Work.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_builder_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_builder_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_builder_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_builders_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_builder_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_builder_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/sw_fireman.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Fireman</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_fireman_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_fireman_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_fireman_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_fireman_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_fireman_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_fireman_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_fireman_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_fireman_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/sw_general.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>General</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_general_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_general_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_general_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_generals_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_general_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_general_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_general_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_general_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
</tr>

<tr><td><img src="../img/0.gif" alt="" width="10" height="40" border="0"></td><td></td><td></td><td></td><td></td><td></td></tr>

<tr>
<td valign="top"><img src="../img/thumb/sw_dragon.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Dragon</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_dragon_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_dragon_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_dragon_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_dragons_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/sw_kamikaze.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Kamikaze</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_kamikaze_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_kamikaze_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_kamikaze_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_kamikaze_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/sw_shotgun.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Shotgun</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_shotgun_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_shotgun_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_shotgun_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_shotgun_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_shotgun_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_shotguns_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_shotgun_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_shotgun_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
</tr>

<tr><td><img src="../img/0.gif" alt="" width="10" height="40" border="0"></td><td></td><td></td><td></td><td></td><td></td></tr>

<tr>
<td valign="top"><img src="../img/thumb/sw_spider.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Spider</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_spider_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_spider_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_spider_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_spider_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_spider_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_spiders_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_spider_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_spider_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_spider_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_spider_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/sw_strag.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Strag</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_strag_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_strag_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_strag_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_strag_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_strag_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_strag_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_strag_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_strag_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
<td valign="top"><img src="../img/thumb/sw_svin.jpg" alt="to view" width="72" height="91" border="0"><img src="../img/0.gif" alt="" width="10" height="20" border="0"></td>
<td valign="top"><div id = "body" class=style1><img src="../img/0.gif" alt="" width="100" height="1" border="0"><br><strong>Svin</strong><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_svin_M2MF')" class = submenu>Fight<img src="../img/0.gif" alt="" width="13" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_svin_M2MF.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_svin_Stay')" class = submenu>Stay<img src="../img/0.gif" alt="" width="16" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_svin_Stay.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_svin_Death')" class = submenu>Death<img src="../img/0.gif" alt="" width="6" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_svins_Death.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_svin_Attack')" class = submenu>Attack<img src="../img/0.gif" alt="" width="5" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_svin_Attack.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a><br><br><a href="javascript:screen_view ('./body/flash.php?file=sw_svin_Move')" class = submenu>Move<img src="../img/0.gif" alt="" width="11" height="1" border="0"><img src="../img/video.gif" alt="to view" width="18" height="15" border="0"></a><a href="../video/sw_svin_Move.flv"><img src="../img/save.gif" alt="" width="22" height="15" border="0"></a></div></td>
</tr>
</table>