<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%tbl_category}}".
 *
 * @property integer $id
 * @property integer $name
 * @property string $create_date
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tbl_category}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
            [['create_date'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'create_date' => 'Create Date',
        ];
    }

    /**
     * @return integer
     */
    public function getJob(){
        
        return $this->hasMany(Job::className(),['category_id'=>'id']);
    }

    public function getUser(){

        return $this->hasOne(User::className(),['id'=>'user_id']);
    }



    public function beforeSave($insert){
        $this->user_id = 1;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
