<?php

namespace app\controllers;

use Yii;

use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;


use app\models\Category;
use yii\data\Pagination;

class CategoryController extends \yii\web\Controller
{
    /*
    * Access Control
   */
    public function behaviors(){

        return [
            'access'=>[
                'class' => AccessControl::className(),
                'only' => ['create','edit','delete'],
                'rules' => [
                    [
                        'actions' => ['create','edit','delete'],
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
        //return parent::behaviors(); // TODO: Change the autogenerated stub
    }
    
    public function actionIndex(){
        //Create Query
        $query = Category::find();

        $pagination = new Pagination([
            'defaultPageSize' => 20,
            'totalCount' => $query->count(),
        ]);

        $categories = $query->orderBy('name')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index',[
            'categories' => $categories,
            'pagination' => $pagination
        ]);
    }

    public function actionCreate(){
        $category = new Category();

        if (Yii::$app->user->identity->id!=1){

            //Redirect
            return $this->redirect('index.php?r=category');
        }
        
        
        if ($category->load(Yii::$app->request->post())) {
            //Validation
            if ($category->validate()) {
                // form inputs are valid, we save it
                $category->save();

                //send Message
                Yii::$app->getSession()->setFlash('success', 'Category Added');

                return $this->redirect('index.php?r=category');
            }
        }

        return $this->render('create', [
            'category' => $category,
        ]);
    }
}
