<?php

namespace app\controllers;

use Yii;

use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

use app\models\Job;
use app\models\Category;
use yii\data\Pagination;

class JobController extends \yii\web\Controller
{
    /*
     * Access Control
    */
    public function behaviors(){

        return [
            'access'=>[
                'class' => AccessControl::className(),
                'only' => ['create','edit','delete'],
                'rules' => [
                    [
                        'actions' => ['create','edit','delete'],
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
        //return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        //Create Query
        $query = Job::find();

        $pagination = new Pagination([
            'defaultPageSize' => 20,
            'totalCount' => $query->count(),
        ]);

        $jobs = $query->orderBy('create_date DESC')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index',[
            'jobs' => $jobs,
            'pagination' => $pagination
        ]);
   }

    public function actionDetails($id){
        //Get Job
        $job  = Job::find()
            ->where(['id'=>$id])
            ->one();
        //Render View
        return $this->render('details', ['job'=>$job]);
    }

    public function actionCreate(){
        $job = new Job();

        if ($job->load(Yii::$app->request->post())) {
            if ($job->validate()) {
                // form inputs are valid, do something here
                $job->save();

                //send Message
                Yii::$app->getSession()->setFlash('success', 'Job Added');

                //Redirect
                return $this->redirect('index.php?r=job');
            }
        }

        return $this->render('create', [
            'job' => $job,
        ]);
    }

    public function actionDelete($id){

        $job = Job::findOne($id);
        if (Yii::$app->user->identity->id!=$job->user_id){

            //Redirect
            return $this->redirect('index.php?r=job');
        }
        $job->delete();

        //send Message
        Yii::$app->getSession()->setFlash('success', 'Job Deleted');

        //Redirect
        return $this->redirect('index.php?r=job');
    }

    public function actionEdit($id){

        $job = Job::findOne($id);

        //Check User identity
        if (Yii::$app->user->identity->id!=$job->user_id){

            //Redirect
            return $this->redirect('index.php?r=job');
        }

        if ($job->load(Yii::$app->request->post())) {
            if ($job->validate()) {
                // form inputs are valid, do something here
                $job->save();

                //send Message
                Yii::$app->getSession()->setFlash('success', 'Job Updated');

                //Redirect
                return $this->redirect('index.php?r=job');
            }
        }

        return $this->render('edit', [
            'job' => $job,
        ]);
    }

}
